In [8]:
import pandas as pd
link = "./BD/df_final.csv"
link2 = "./BD/movies.csv"

df_tmdb_clean = pd.read_csv(link)
movies = pd.read_csv(link2)

In [9]:
df_tmdb_clean

,ID,Titre,Date de sortie,Durée (minutes),Genres,Langue Originale,Note moyenne,Nb de votes,Score de popularité,Résumé,Lien du poster,Budget,ID_tmdb,Titres possibles,Décénnie,Liste acteurs,Réalisateurs
0,tt0054759,Come September,1961-01-01,112,"['Comedy', 'Romance']",en,6.900,65,10.214,"Robert Talbot, an American millionaire, arrive...",/6gZXuejbB3yfZrZkIs8u8Wfs8s4.jpg,0,22386,"['Möte i September', 'Приходи в сентябре', '九月...",1960,"['Rock Hudson', 'Gina Lollobrigida', 'Sandra D...",['Robert Mulligan']
1,tt0055254,One Hundred and One Dalmatians,1961-01-25,82,"['Adventure', 'Animation', 'Comedy', 'Family']",en,7.167,5646,47.549,When a litter of dalmatian puppies are abducte...,/mRY84MJeWKnp9joev82QtslJFvk.jpg,4000000,12230,"['101 dalmatiyalı', 'De nacht van de kouwe neu...",1960,"['Rod Taylor', 'Betty Lou Gerson', ""J. Pat O'M...","['Clyde Geronimi', 'Hamilton Luske', 'Wolfgang..."
2,tt0055184,The Misfits,1961-02-01,124,"['Western', 'Drama', 'Action', 'Romance']",en,6.942,310,13.136,"While filing for a divorce, beautiful ex-strip...",/pjWlNZeoT5ZcVutOAHkFK7Z22Sb.jpg,4000000,11536,"['Skłóceni z życiem', 'Inadaptabilii', 'Mustan...",1960,"['Clark Gable', 'Marilyn Monroe', 'Montgomery ...",['John Huston']
3,tt0054938,Gorgo,1961-02-02,78,"['Science Fiction', 'Action', 'Horror']",en,5.404,68,7.892,Greedy sailors capture a giant lizard off the ...,/8Bs4AmPxmlwHHeGz8QAEsivsgtT.jpg,650000,40804,"['Gorgo: Havets uhyre', 'Kaijû Gorugo', 'Gorgo...",1960,"['Bill Travers', 'William Sylvester', 'Vincent...",['Eugène Lourié']
4,tt0055571,Underworld U.S.A.,1961-02-22,99,"['Crime', 'Drama', 'Thriller']",en,6.900,65,4.572,A bitter young man sets out to get back at the...,/xPlQikmoHV1Rt1n0lwVYXkbWR0I.jpg,0,28699,"['Alles auf eine Karte', ""Ο υπ' αριθ. 1 εχθρός...",1960,"['Cliff Robertson', 'Dolores Dorn', 'Beatrice ...",['Samuel Fuller']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16986,tt23219684,Mighty Morphin Power Rangers: Once & Always,2023-04-19,59,"['Action', 'Adventure', 'Science Fiction', 'Fa...",en,6.783,161,97.924,"After tragedy strikes, an unlikely young hero ...",/vc87upO8vcAGj9OmgH3AIz6ikKB.jpg,0,1068141,"['Power Rangers: Ayer, hoy y siempre', 'Могучи...",2020,"['Walter Jones', 'Steve Cardenas', 'Catherine ...",['Charlie Haskell']
16987,tt5635026,Peter Pan & Wendy,2023-04-20,106,"['Family', 'Fantasy', 'Action', 'Adventure']",en,5.895,277,1358.468,"Wendy Darling, a young girl afraid to leave he...",/9NXAlFEE7WDssbXSMgdacsUD58Y.jpg,0,420808,"['Peter Pan e Wendy', 'Piotruś Pan i Wendy', '...",2020,"['Alexander Molony', 'Ever Anderson', 'Jude La...",['David Lowery']
16988,tt20115096,A Tourist's Guide to Love,2023-04-21,96,"['Romance', 'Comedy', 'Adventure']",en,6.543,69,161.027,"After an unexpected break up, a travel executi...",/uWkpjbBe4gRZilXRXbYfsMUZMhz.jpg,0,813726,"['Útikönyv a szerelemhez', 'Маршрут до кохання...",2020,"['Rachael Leigh Cook', 'Scott Ly', 'Ben Feldma...",['Steven K. Tsuchida']
16989,tt27197387,AKA,2023-04-28,122,"['Thriller', 'Action', 'Crime']",fr,7.024,148,988.329,A steely special ops agent finds his morality ...,/3BSxAjiporlwQTWzaHZ9Yrl5C9D.jpg,0,1102776,"['AKA', 'Также известный', 'Kimdim Ben?', 'Ali...",2020,"['Alban Lenoir', 'Éric Cantona', 'Thibault de ...",['Morgan S. Dalibert']
16990,tt6791350,Guardians of the Galaxy Volume 3,2023-05-03,150,"['Science Fiction', 'Adventure', 'Action']",en,8.300,710,2520.308,"Peter Quill, still reeling from the loss of Ga...",/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg,250000000,447365,"['Пазители на Галактиката 3', 'Чувари на галак...",2020,"['Chris Pratt', 'Chukwudi Iwuji', 'Bradley Coo...",['James Gunn']

In [23]:
df_tmdb_clean['Genres'] = df_tmdb_clean['Genres'].apply(lambda x: eval(x))

In [24]:
movies =df_tmdb_clean.join(df_tmdb_clean['Genres'].explode().str.get_dummies().groupby(level=0).sum()*3)
movies

,ID,Titre,Date de sortie,Durée (minutes),Genres,Langue Originale,Note moyenne,Nb de votes,Score de popularité,Résumé,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
0,tt0082812,Night School,1981-01-07,88,"[Horror, Mystery, Thriller]",en,5.800,53,5.284,A Boston police detective investigates a serie...,...,0,3,0,3,0,0,0,3,0,0
1,tt0086262,Scream,1981-01-08,82,"[Horror, Mystery]",en,4.128,43,12.860,A group of friends on a rafting trip down a ri...,...,0,3,0,3,0,0,0,0,0,0
2,tt0081455,Scanners,1981-01-14,103,"[Science Fiction, Horror]",en,6.738,1001,11.191,After a man with extraordinary—and frightening...,...,0,3,0,0,0,3,0,0,0,0
3,tt0082533,The Howling,1981-01-21,91,[Horror],en,6.563,641,17.589,After a bizarre and near fatal encounter with ...,...,0,3,0,0,0,0,0,0,0,0
4,tt0084090,Inseminoid,1981-01-23,93,"[Thriller, Horror, Science Fiction]",en,3.939,74,8.075,A crew of interplanetary archaeologists is thr...,...,0,3,0,0,0,3,0,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16226,tt23219684,Mighty Morphin Power Rangers: Once & Always,2023-04-19,59,"[Action, Adventure, Science Fiction, Family]",en,6.783,161,97.924,"After tragedy strikes, an unlikely young hero ...",...,0,0,0,0,0,3,0,0,0,0
16227,tt5635026,Peter Pan & Wendy,2023-04-20,106,"[Family, Fantasy, Action, Adventure]",en,5.895,277,1358.468,"Wendy Darling, a young girl afraid to leave he...",...,0,0,0,0,0,0,0,0,0,0
16228,tt20115096,A Tourist's Guide to Love,2023-04-21,96,"[Romance, Comedy, Adventure]",en,6.543,69,161.027,"After an unexpected break up, a travel executi...",...,0,0,0,0,3,0,0,0,0,0
16229,tt27197387,AKA,2023-04-28,122,"[Thriller, Action, Crime]",fr,7.024,148,988.329,A steely special ops agent finds his morality ...,...,0,0,0,0,0,0,0,3,0,0
16230,tt6791350,Guardians of the Galaxy Volume 3,2023-05-03,150,"[Science Fiction, Adventure, Action]",en,8.300,710,2520.308,"Peter Quill, still reeling from the loss of Ga...",...,0,0,0,0,0,3,0,0,0,0

In [25]:
movies= movies.drop(columns=['Genres', 'Date de sortie', 'Résumé', 'Lien du poster', 'Budget', 'Titres possibles', 'Nb de votes','Liste acteurs','Réalisateurs'])
movies.to_csv('movies.csv', index=False)
movies

,ID,Titre,Durée (minutes),Langue Originale,Note moyenne,Score de popularité,Décénnie,Action,Adventure,Animation,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
0,tt0082812,Night School,88,en,5.800,5.284,1980,0,0,0,...,0,3,0,3,0,0,0,3,0,0
1,tt0086262,Scream,82,en,4.128,12.860,1980,0,0,0,...,0,3,0,3,0,0,0,0,0,0
2,tt0081455,Scanners,103,en,6.738,11.191,1980,0,0,0,...,0,3,0,0,0,3,0,0,0,0
3,tt0082533,The Howling,91,en,6.563,17.589,1980,0,0,0,...,0,3,0,0,0,0,0,0,0,0
4,tt0084090,Inseminoid,93,en,3.939,8.075,1980,0,0,0,...,0,3,0,0,0,3,0,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16226,tt23219684,Mighty Morphin Power Rangers: Once & Always,59,en,6.783,97.924,2020,3,3,0,...,0,0,0,0,0,3,0,0,0,0
16227,tt5635026,Peter Pan & Wendy,106,en,5.895,1358.468,2020,3,3,0,...,0,0,0,0,0,0,0,0,0,0
16228,tt20115096,A Tourist's Guide to Love,96,en,6.543,161.027,2020,0,3,0,...,0,0,0,0,3,0,0,0,0,0
16229,tt27197387,AKA,122,fr,7.024,988.329,2020,3,0,0,...,0,0,0,0,0,0,0,3,0,0
16230,tt6791350,Guardians of the Galaxy Volume 3,150,en,8.300,2520.308,2020,3,3,0,...,0,0,0,0,0,3,0,0,0,0

In [2]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
movies[['Note moyenne', 'Score de popularité', 'Décénnie','Durée (minutes)']] = scaler.fit_transform(movies[['Note moyenne', 'Score de popularité', 'Décénnie','Durée (minutes)']])

In [4]:
from sklearn.neighbors import NearestNeighbors

def mes_recommendations(movie_title, nb_films=5):
    if movie_title not in movies['Titre'].values:
        return "Le film demandé n'est pas dans la base de données."

    # je supprime les lignes et je donne du poids à chaque colonne
    features = movies.drop(columns=['ID','Titre','Langue Originale'])
    features['Décénnie'] *= 2.5
    features['Score de popularité'] *= 2
    features['Note moyenne'] *= 1.5
    features['Durée (minutes)'] *= 1

    # j'entraîne le modèle
    knn = NearestNeighbors(n_neighbors=nb_films+1, metric='cosine')
    knn.fit(features)

    # je recherche l'id des films recommandés
    movie_index = movies[movies['Titre'] == movie_title].index[0]
    distances, indices = knn.kneighbors(features.iloc[movie_index].values.reshape(1, -1))
    recommended_movie_ids = movies.iloc[indices[0][1:]]['ID'].values

    # je commence la partie de recommendation de  films français ici 
    french_movies = movies[movies['Langue Originale'] == 'fr']
    filtered_movies = french_movies[~french_movies['ID'].isin(recommended_movie_ids)]

    # je supprime les lignes et je donne du poids à chaque colonne
    filtered_features = filtered_movies.drop(columns=[ 'ID','Titre','Langue Originale'])
    features['Décénnie'] *= 2.5
    features['Score de popularité'] *= 2
    features['Note moyenne'] *= 1.5
    features['Durée (minutes)'] *= 1

    # j'entraîne le modèle
    knn_filtered = NearestNeighbors(n_neighbors=nb_films, metric='cosine')
    knn_filtered.fit(filtered_features)
    
    # je recherche l'id des films français à  recommandés
    french_distances, french_indices = knn_filtered.kneighbors(features.iloc[movie_index].values.reshape(1, -1))
    recommended_french_movie_ids = filtered_movies.iloc[french_indices[0]]['ID'].values

    return {
        "Recommandations générales": list(recommended_movie_ids),
        "Recommandations en français": list(recommended_french_movie_ids)
    }

resultat = mes_recommendations('Night School', 8)

c:\Users\Antoine\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(
c:\Users\Antoine\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(

In [5]:
resultat

{'Recommandations générales': ['tt0085694',
  'tt0082951',
  'tt0091799',
  'tt0090327',
  'tt0087472',
  'tt0091080',
  'tt0096152',
  'tt0124014'],
 'Recommandations en français': ['tt0338095',
  'tt2473750',
  'tt1075113',
  'tt0120401',
  'tt0856288',
  'tt1426352',
  'tt0465203',
  'tt0367000']}

In [10]:
df_reco = df_tmdb_clean[df_tmdb_clean['ID'].isin(resultat["Recommandations générales"])]

In [11]:
df_reco

,ID,Titre,Date de sortie,Durée (minutes),Genres,Langue Originale,Note moyenne,Nb de votes,Score de popularité,Résumé,Lien du poster,Budget,ID_tmdb,Titres possibles,Décénnie,Liste acteurs,Réalisateurs
1825,tt0082951,The Prowler,1981-11-06,89,"['Horror', 'Thriller', 'Mystery']",en,5.956,170,8.722,"A masked killer, wearing World War II U.S. Arm...",/4soFiMOul6GRN889FxfDNAt9Woh.jpg,1000000,44247,"['Вбивця Розмарі', 'Убиецът на Роузмари', 'Le ...",1980,"['Vicky Dawson', 'Christopher Goutman', 'Lawre...",['Joseph Zito']
1958,tt0085694,The House on Sorority Row,1982-11-19,91,"['Horror', 'Mystery', 'Thriller']",en,5.800,173,8.797,After a seemingly innocent prank goes horribly...,/x2e22IVGkbCNCCDcw4gg5HezrSQ.jpg,425000,40229,"['The House on Sorority Row', ""Le pensionnat d...",1980,"['Kate McNeil', 'Eileen Davidson', 'Janis Ward...",['Mark Rosman']
2222,tt0087472,The Initiation,1984-12-07,97,"['Horror', 'Mystery', 'Thriller']",en,5.600,74,7.509,An amnesiac sorority member who has been plagu...,/aB5StCoFjvFoywKT2SzmcvECBRl.jpg,0,63360,"['Voeux sanglants', 'Inicjacja', 'Иницијација'...",1980,"['Vera Miles', 'Clu Gulager', 'Daphne Zuniga',...",['Larry Stewart']
2234,tt0124014,The Mutilator,1985-01-04,86,"['Horror', 'Mystery', 'Thriller']",en,5.198,86,5.365,"As a child, Ed was cleaning his father’s hunti...",/WdTypYAKttmUPWMQ4uLzRS6Hye.jpg,0,40451,"['Farligt mörker', 'El mutilador', 'Fall break...",1980,"['Matt Mitler', 'Ruth Martinez', 'Bill Hitchco...",['Buddy Cooper']
2435,tt0091799,Psycho III,1986-04-02,93,"['Horror', 'Thriller', 'Mystery']",en,5.540,313,7.722,Norman Bates is still running his little motel...,/yYY0a3IAitmF8Gg6n98gqxcUREq.jpg,8400000,12662,"['Psyko III', 'Psicosis III', 'Psiho III', 'Ps...",1980,"['Anthony Perkins', 'Diana Scarwid', 'Jeff Fah...",['Anthony Perkins']
2485,tt0091080,Friday the 13th Part VI: Jason Lives,1986-08-01,86,"['Horror', 'Mystery', 'Thriller']",en,6.210,980,24.458,"Tommy Jarvis, tormented by the fear that Jason...",/3qyCfzwY418lbuFEaKX5rKxKlnJ.jpg,3000000,10225,"['Fredag den 13. del VI - Jason lever', 'Piato...",1980,"['Thom Mathews', 'Jennifer Cooke', 'David Kage...",['Tom McLoughlin']
2560,tt0090327,Witchboard,1986-12-31,98,"['Horror', 'Mystery', 'Thriller']",en,5.820,153,4.989,"Playing around with a Ouija board, a trio of f...",/61bQWlNEnNw4CSbaL6HVuXRw0In.jpg,2000000,17994,"['La cuija asesina', 'Démoni játék', 'Spiritik...",1980,"['Todd Allen', 'Tawny Kitaen', 'Stephen Nichol...",['Kevin Tenney']
2878,tt0096152,Spellbinder,1988-09-23,99,"['Horror', 'Thriller', 'Mystery']",en,6.036,56,6.690,"After leaving work one night, Los Angeles atto...",/lthWQAcAmcJ3InuauNuCMgqEVHX.jpg,0,36778,"['La trampa de la araña', 'Noiduttu', 'Στα δεσ...",1980,"['Tim Daly', 'Kelly Preston', 'Rick Rossovich'...",['Janet Greek']

In [31]:
resultat["Recommandations en français"][0][1]

'tt0338095'